app = "mobiledev-relay"
primary_region = "lax"

[build]
  image = "flyio/node:latest"

[env]
  PORT = "3001"

[[services]]
  protocol = "tcp"
  internal_port = 3001

  [[services.ports]]
    number = 443
    handlers = ["tls", "http"]
  [[services.ports]]
    number = 80
    handlers = ["http"]
    force_https = true
